import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(request: Request) {
  try {
    const { to, subject, body } = await request.json();

    if (!to || !subject || !body) {
      return NextResponse.json(
        { error: 'Missing required fields: to, subject, body' },
        { status: 400 },
      );
    }

    // ─────────────────────────────────────────────────────
    // Configure your SMTP transport.
    //
    // Set these environment variables in .env.local:
    //   SMTP_HOST=smtp.gmail.com
    //   SMTP_PORT=587
    //   SMTP_USER=your-email@gmail.com
    //   SMTP_PASS=your-app-password
    //   SMTP_FROM=your-email@gmail.com
    //
    // For Gmail: enable 2FA, then create an App Password at
    //   https://myaccount.google.com/apppasswords
    // ─────────────────────────────────────────────────────
    const smtpHost = process.env.SMTP_HOST;
    const smtpPort = Number(process.env.SMTP_PORT || '587');
    const smtpUser = process.env.SMTP_USER;
    const smtpPass = process.env.SMTP_PASS;
    const smtpFrom = process.env.SMTP_FROM || smtpUser;

    if (!smtpHost || !smtpUser || !smtpPass) {
      return NextResponse.json(
        {
          error:
            'Email not configured. Set SMTP_HOST, SMTP_USER, and SMTP_PASS in .env.local — see README for details.',
        },
        { status: 503 },
      );
    }

    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpPort === 465,
      auth: {
        user: smtpUser,
        pass: smtpPass,
      },
    });

    // Build HTML version of the LOI for nicer formatting
    const htmlBody = `
      <div style="font-family: 'Courier New', monospace; background: #0f172a; color: #e2e8f0; padding: 32px; border-radius: 12px;">
        <div style="max-width: 700px; margin: 0 auto;">
          <div style="text-align: center; margin-bottom: 24px; padding-bottom: 16px; border-bottom: 1px solid rgba(255,255,255,0.1);">
            <h1 style="color: #22d3ee; font-size: 24px; margin: 0;">LEVIATHAN</h1>
            <p style="color: #64748b; font-size: 11px; text-transform: uppercase; letter-spacing: 3px; margin-top: 4px;">Autonomous Procurement Intelligence</p>
          </div>
          <pre style="white-space: pre-wrap; word-wrap: break-word; font-size: 13px; line-height: 1.6; color: #cbd5e1;">${body.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
          <div style="margin-top: 24px; padding-top: 16px; border-top: 1px solid rgba(255,255,255,0.1); text-align: center;">
            <p style="color: #475569; font-size: 10px; text-transform: uppercase; letter-spacing: 2px;">Generated by LEVIATHAN Swarm v4.2.1</p>
          </div>
        </div>
      </div>
    `;

    const info = await transporter.sendMail({
      from: `"LEVIATHAN Swarm" <${smtpFrom}>`,
      to,
      subject,
      text: body,
      html: htmlBody,
    });

    return NextResponse.json({
      success: true,
      messageId: info.messageId,
    });
  } catch (error) {
    console.error('[LEVIATHAN] Email send error:', error);
    return NextResponse.json(
      {
        error:
          error instanceof Error
            ? error.message
            : 'Failed to send email. Check SMTP configuration.',
      },
      { status: 500 },
    );
  }
}
