'use client';

import { useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Download, Mail, Copy, Check } from 'lucide-react';
import { useSwarmStore } from '@/store/useSwarmStore';
import { useState } from 'react';

export default function DocumentModal() {
  const showDocumentModal = useSwarmStore((s) => s.showDocumentModal);
  const setShowDocumentModal = useSwarmStore((s) => s.setShowDocumentModal);
  const setShowEmailModal = useSwarmStore((s) => s.setShowEmailModal);
  const generatedLOI = useSwarmStore((s) => s.generatedLOI);
  const [copied, setCopied] = useState(false);

  const handleClose = useCallback(() => {
    setShowDocumentModal(false);
  }, [setShowDocumentModal]);

  const handleCopy = useCallback(async () => {
    if (!generatedLOI) return;
    await navigator.clipboard.writeText(generatedLOI);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [generatedLOI]);

  const handleDownload = useCallback(() => {
    if (!generatedLOI) return;
    const blob = new Blob([generatedLOI], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Leviathan_LOI_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [generatedLOI]);

  const handleSendEmail = useCallback(() => {
    setShowDocumentModal(false);
    setTimeout(() => setShowEmailModal(true), 150);
  }, [setShowDocumentModal, setShowEmailModal]);

  return (
    <AnimatePresence>
      {showDocumentModal && (
        <motion.div
          className="fixed inset-0 z-[100] flex items-center justify-center"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
        >
          {/* Backdrop */}
          <motion.div
            className="absolute inset-0 bg-black/70 backdrop-blur-sm"
            onClick={handleClose}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
          />

          {/* Modal */}
          <motion.div
            className="relative flex max-h-[85vh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl border border-white/10 bg-slate-900 shadow-2xl shadow-violet-500/10"
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            transition={{ type: 'spring', damping: 25, stiffness: 300 }}
          >
            {/* Header */}
            <div className="flex items-center justify-between border-b border-white/10 px-6 py-4">
              <div>
                <h2 className="text-lg font-semibold text-white">
                  Letter of Intent
                </h2>
                <p className="mt-0.5 text-xs text-slate-500">
                  Generated by LEVIATHAN Swarm v4.2.1
                </p>
              </div>
              <button
                onClick={handleClose}
                className="flex h-8 w-8 items-center justify-center rounded-lg border border-white/10 transition-all hover:border-white/20 hover:bg-white/5"
              >
                <X className="h-4 w-4 text-slate-400" />
              </button>
            </div>

            {/* Document body */}
            <div className="flex-1 overflow-y-auto px-6 py-5">
              {generatedLOI ? (
                <pre className="whitespace-pre-wrap break-words font-mono text-sm leading-relaxed text-slate-300">
                  {generatedLOI}
                </pre>
              ) : (
                <p className="text-center text-slate-500">
                  No document generated yet.
                </p>
              )}
            </div>

            {/* Footer actions */}
            <div className="flex items-center justify-between border-t border-white/10 px-6 py-4">
              <div className="flex gap-2">
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-2 rounded-lg border border-white/10 px-4 py-2 text-xs font-medium text-slate-300 transition-all hover:border-white/20 hover:bg-white/5"
                >
                  {copied ? (
                    <Check className="h-3.5 w-3.5 text-emerald-400" />
                  ) : (
                    <Copy className="h-3.5 w-3.5" />
                  )}
                  {copied ? 'Copied!' : 'Copy'}
                </button>
                <button
                  onClick={handleDownload}
                  className="flex items-center gap-2 rounded-lg border border-white/10 px-4 py-2 text-xs font-medium text-slate-300 transition-all hover:border-white/20 hover:bg-white/5"
                >
                  <Download className="h-3.5 w-3.5" />
                  Download
                </button>
              </div>
              <button
                onClick={handleSendEmail}
                className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-cyan-500 to-violet-500 px-5 py-2 text-xs font-semibold text-white shadow-lg shadow-cyan-500/20 transition-all hover:shadow-cyan-500/30"
              >
                <Mail className="h-3.5 w-3.5" />
                Send via Email
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
